#spring.kafka.bootstrap-servers=localhost:9092
spring.profiles.active=local

spring.application.name=device-simulator-service
#spring.profiles.active=docker
spring.kafka.bootstrap-servers=localhost:9092
server.port=8081
simulator.topic-name=network-events-raw
simulator.device-count=500
simulator.publish-interval=5000
simulator.device-prefix=DEVICE
logging.level.root=INFO
logging.level.com.hcl.nms.simulator=DEBUG